### ISSUE TITLE
Upload to hackage

### ISSUE THREAD

**Issue by dbaynard** [dbaynard/lucid-from-html#2]
It would be good to get some feedback, stabilize, then upload to hackage.

Alternatively, it could be integrated right back into lucid (see chrisdone/lucid#70).

**Comment by alogic0** [comment]
Hi, David!
I'm still sure that the project should be published on the Hackage separately. The more sites I'm testing it on, the more elements that are not in HTML5 and hence cannot be included in the Lucid come to [an additional file](https://github.com/alogic0/lucid-from-html/blob/svg/src/Lucid/Supplemental.hs), that extends the Lucid library. 

If you add the ability to parse the `<svg>` tag, using `lucid-svg` the project will depend on that `lucid-svg` but the original Lucid won't be happy from such additional dependency. 

So, it's better not mix two projects and solve the tasks of writing HTML5 and parsing the zoo of existing pages in a distinct packages.

**Comment by dbaynard** [comment]
Yeah, go ahead then. You should take ownership of the project; it seems like you're making good use of it.

**Comment by alogic0** [comment]
Thank you for the trust. I was learning by hacking your code and your license is in the project. I will appreciate any further suggestions.
